version: '3.4'

services:
  lobster.web.demo:
    image: lobster.web.demo
    build:
      context: .
      dockerfile: Lobster.Web.Demo/Dockerfile
    container_name: lobster.web.demo
  lobster.service.demo:
    image: lobster.service.demo
    build:
      context: .
      dockerfile: Lobster.Service.Demo/Dockerfile
    container_name: lobster.service.demo
  lobster.quartz:
    image: lobster.quartz
    build:
      context: .
      dockerfile: Lobster.Quartz/Dockerfile
    container_name: lobster.quartz
  lobster.gateway:
    image: lobster.gateway
    build:
      context: .
      dockerfile: Lobster.Gateway/Dockerfile
    container_name: lobster.gateway