version: '3.4'

services:
  lobster.web.demo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"
      - "5101:443"
    restart: always
  lobster.service.demo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
      - "5001:443"
    restart: always