version: '3.4'

services:
  lobster.web.demo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Shanghai
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
    ports:
      - "5100:80"
      - "5101:443"
    restart: always
  lobster.service.demo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Shanghai
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
    ports:
      - "5000:80"
      - "5001:443"
    restart: always
  lobster.quartz:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Shanghai
    ports:
      - "5200:80"
    restart: always
  lobster.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Shanghai
    ports:
      - "5500:80"
      - "5501:443"
    restart: always